# Label Encoding(rank)

#### disadv?

In [4]:
import pandas as pd 

df = pd.DataFrame(
    {
        'color' : ["red",'green','red','blue','yellow','orange']
    }
)

In [5]:
from sklearn.preprocessing import LabelEncoder

lbl = LabelEncoder()

lbl.fit_transform(df[['color']])

d:\Anaconda\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([3, 1, 3, 0, 4, 2])

In [6]:
lbl.transform([['blue']])

d:\Anaconda\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

In [7]:
lbl.transform([['red']])

d:\Anaconda\Lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([3])

# Ordinal Encoding

In [25]:
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd

ord = OrdinalEncoder(categories=[['small','medium','large']])

In [33]:
data = ["medium", "large", "small", 'large','large', 'small', 'medium' ]

df =pd.DataFrame({
     "size" : data
     })

In [34]:
df

     size
0  medium
1   large
2   small
3   large
4   large
5   small
6  medium

In [35]:
ord.fit_transform(df[['size']])

array([[1.],
       [2.],
       [0.],
       [2.],
       [2.],
       [0.],
       [1.]])

# Target Guided Ordinal Encoding

In [38]:
df2 =  pd.DataFrame(
    {
        'city' : ['a', 'b', 'c', 'a', 'c', 'b', 'c'],
        'price' : [3,4,2,5,7,1,1]
    }
)

len(df2[['city']])

7

In [39]:
df2

  city  price
0    a      3
1    b      4
2    c      2
3    a      5
4    c      7
5    b      1
6    c      1

In [46]:
mean_price = df2.groupby('city')['price'].mean().to_dict()

In [47]:
df2['city_encoded'] = df2['city'].map(mean_price)

In [49]:
df2[['city',"city_encoded","price"]]

  city  city_encoded  price
0    a      4.000000      3
1    b      2.500000      4
2    c      3.333333      2
3    a      4.000000      5
4    c      3.333333      7
5    b      2.500000      1
6    c      3.333333      1

In [52]:
median_price = df2.groupby('city')['price'].median().to_dict()

In [53]:
df2['city_encoded_median'] = df2['city'].map(median_price)

In [54]:
df2

  city  price  city_encoded  city_encoded_median
0    a      3      4.000000                  4.0
1    b      4      2.500000                  2.5
2    c      2      3.333333                  2.0
3    a      5      4.000000                  4.0
4    c      7      3.333333                  2.0
5    b      1      2.500000                  2.5
6    c      1      3.333333                  2.0